force-app/main/default/objects/AutomatedTestSetup__mdt/AutomatedTestSetup__mdt.object-meta.xml
<CustomObject>
    <label>Automated Test Setup</label>
    <pluralLabel>Automated Test Setups</pluralLabel>
</CustomObject>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/Cron__c.field-meta.xml
<CustomField>
    <fullName>Cron__c</fullName>
    <description>This is the schedule the tests will run on.</description>
    <inlineHelpText>See the Apex Scheduler documentation for how to write cron expressions</inlineHelpText>
    <label>Cron</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ExcludedClasses__c.field-meta.xml
<CustomField>
    <fullName>ExcludedClasses__c</fullName>
    <description>These Apex test classes will NOT be run, regardless of a defined Test Name Pattern.</description>
    <inlineHelpText>Takes a comma-separated list of Apex classes</inlineHelpText>
    <label>Excluded Classes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/MinutesToWait__c.field-meta.xml
<CustomField>
    <fullName>MinutesToWait__c</fullName>
    <defaultValue>30</defaultValue>
    <description>The Automated Test Runner will check in intervals of [this] many minutes to see if the test run is complete.</description>
    <label>Minutes To Wait</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/TestNamePattern__c.field-meta.xml
<CustomField>
    <fullName>TestNamePattern__c</fullName>
    <description>Filter the test classes to run to only include those that match this SOQL pattern, ex: %bacon%. Do not include any quotes.</description>
    <inlineHelpText>See the SOQL Refernce for how to use the LIKE operator</inlineHelpText>
    <label>Test Name Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/UserIds__c.field-meta.xml
<CustomField>
    <fullName>UserIds__c</fullName>
    <description>Users defined here will be emailed the test results. These will be combined with users in any configured profile or permission set.</description>
    <inlineHelpText>Takes a comma-separated list of User IDs</inlineHelpText>
    <label>User Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AutomatedTestRunner_Test.cls
@IsTest
class AutomatedTestRunner_Test {
  static final String CUSTOM_METADATA_JSON =
    '[{"Label": "blah", "Cron__c": "0 0 2 * * ?", "MinutesToWait__c": "30", "TestNamePattern__c": "%blah%", "ExcludedClasses__c": "skipme", "UserIds__c": "' +
    UserInfo.getUserId() +
    '"},{"Label": "blah2", "Cron__c": "0 0 2 * * ?", "MinutesToWait__c": "30", "TestNamePattern__c": "%blah%", "UserIds__c": "' +
    UserInfo.getUserId() +
    '"}]';

  static final String APEX_CLASS_JSON = '[ { "NamespacePrefix": null, "Name": "blah"} ]';

  @IsTest
  static void testConstructor() {
    List<AutomatedTestSetup__mdt> testSetups = (List<AutomatedTestSetup__mdt>) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      List<AutomatedTestSetup__mdt>.class
    );

    AutomatedTestRunner.testSetups = testSetups;

    Test.startTest();
    AutomatedTestRunner testRunner = new AutomatedTestRunner(testSetups[0]);
    Test.stopTest();

    Assert.areEqual(testSetups[0], testRunner.testSetup);
  }

  @IsTest
  static void testSetup() {
    List<AutomatedTestSetup__mdt> testSetups = (List<AutomatedTestSetup__mdt>) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      List<AutomatedTestSetup__mdt>.class
    );

    AutomatedTestRunner.testSetups = testSetups;
    AutomatedTestRunner.apexClasses = new List<ApexClass>();

    Test.startTest();
    AutomatedTestRunner.run();
    Test.stopTest();

    Integer numberOfScheduledJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status = 'Queued' AND ApexClass.Name = 'AutomatedTestRunner'
    ];

    Assert.areEqual(testSetups.size(), numberOfScheduledJobs);

    numberOfScheduledJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status = 'Queued' AND ApexClass.Name = 'AutomatedTestReport'
    ];

    Assert.areEqual(0, numberOfScheduledJobs);
  }

  @IsTest
  static void testSetupWithDefinedConfigAndCron() {
    List<AutomatedTestSetup__mdt> testSetups = (List<AutomatedTestSetup__mdt>) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      List<AutomatedTestSetup__mdt>.class
    );

    AutomatedTestRunner.testSetups = new List<AutomatedTestSetup__mdt>{
      testSetups[0]
    };

    Test.startTest();
    AutomatedTestRunner.run(testSetups[1].Label, '0 0 3 * * ?');
    Test.stopTest();

    Integer numberOfScheduledJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status = 'Queued' AND ApexClass.Name = 'AutomatedTestRunner'
    ];

    Assert.areEqual(1, numberOfScheduledJobs);
  }

  @IsTest
  static void testAlreadyScheduled() {
    List<AutomatedTestSetup__mdt> testSetups = (List<AutomatedTestSetup__mdt>) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      List<AutomatedTestSetup__mdt>.class
    );

    AutomatedTestRunner.testSetups = testSetups;
    AutomatedTestRunner.apexClasses = new List<ApexClass>();
    AutomatedTestRunner.run();

    Test.startTest();
    AutomatedTestRunner.run();
    Test.stopTest();

    Integer numberOfScheduledJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status = 'Queued' AND ApexClass.Name = 'AutomatedTestRunner'
    ];

    Assert.areEqual(testSetups.size(), numberOfScheduledJobs);
  }

  @IsTest
  static void testApexClassRetrievalAndTestKickoff() {
    List<AutomatedTestSetup__mdt> testSetups = (List<AutomatedTestSetup__mdt>) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      List<AutomatedTestSetup__mdt>.class
    );
    List<ApexClass> apexClasses = (List<ApexClass>) JSON.deserialize(
      APEX_CLASS_JSON,
      List<ApexClass>.class
    );

    AutomatedTestRunner.testSetups = testSetups;
    AutomatedTestRunner.apexClasses = apexClasses;

    Test.startTest();
    AutomatedTestRunner.run();
    Test.stopTest();

    Integer numberOfScheduledJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status = 'Queued' AND ApexClass.Name = 'AutomatedTestReport'
    ];

    Assert.areEqual(apexClasses.size(), numberOfScheduledJobs);
  }

  @IsTest
  static void customMetadataQueryAndSoslCoverage() {
    AutomatedTestSetup__mdt testSetup = ((List<AutomatedTestSetup__mdt>) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      List<AutomatedTestSetup__mdt>.class
    ))[0];

    AutomatedTestRunner.getAutomatedTestSetups(null);
    AutomatedTestRunner.getApexTestClasses(testSetup);
  }
}