force-app/main/default/objects/AutomatedTestSetup__mdt/AutomatedTestSetup__mdt.object-meta.xml
<CustomObject>
    <label>Automated Test Setup</label>
    <pluralLabel>Automated Test Setups</pluralLabel>
</CustomObject>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/Cron__c.field-meta.xml
<CustomField>
    <fullName>Cron__c</fullName>
    <description>This is the schedule the tests will run on.</description>
    <inlineHelpText>See the Apex Scheduler documentation for how to write cron expressions</inlineHelpText>
    <label>Cron</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ExcludedClasses__c.field-meta.xml
<CustomField>
    <fullName>ExcludedClasses__c</fullName>
    <description>These Apex test classes will NOT be run, regardless of a defined Test Name Pattern.</description>
    <inlineHelpText>Takes a comma-separated list of Apex classes</inlineHelpText>
    <label>Excluded Classes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ExcludedUserIds__c.field-meta.xml
<CustomField>
    <fullName>ExcludedUserIds__c</fullName>
    <description>Users defined here will NOT be emailed, regardless of whether they meet other configured criteria.</description>
    <inlineHelpText>Takes a comma-separated list of User IDs</inlineHelpText>
    <label>Excluded User Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/IncludeNamespacedClasses__c.field-meta.xml
<CustomField>
    <fullName>IncludeNamespacedClasses__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, namespaced, i.e. packaged, classes, will be in included in the test run.</description>
    <label>Include Namespaced Classes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this test configuration will be scheduled when the Automated Test Runner is launched. Unchecking already active scheduled test runs will not unschedule them. The associated scheduled job must be deleted.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/MinutesToWait__c.field-meta.xml
<CustomField>
    <fullName>MinutesToWait__c</fullName>
    <defaultValue>30</defaultValue>
    <description>The Automated Test Runner will check in intervals of [this] many minutes to see if the test run is complete.</description>
    <label>Minutes To Wait</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/PermissionSetToEmail__c.field-meta.xml
<CustomField>
    <fullName>PermissionSetToEmail__c</fullName>
    <description>Users of this permission set will be emailed the test results. These will be combined with users in any configured profile or list of user IDs.</description>
    <inlineHelpText>Takes a permission set&apos;s API name</inlineHelpText>
    <label>Permission Set To Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ProfileToEmail__c.field-meta.xml
<CustomField>
    <fullName>ProfileToEmail__c</fullName>
    <description>Users of this profile will be emailed the test results. These will be combined with users in any configured permission set or list of user IDs.</description>
    <inlineHelpText>Takes a profile name</inlineHelpText>
    <label>Profile To Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ShowStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ShowStackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, the stack traces for failed tests will be included in the emailed report.</description>
    <label>Show Stack Trace</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/TestNamePattern__c.field-meta.xml
<CustomField>
    <fullName>TestNamePattern__c</fullName>
    <description>Filter the test classes to run to only include those that match this SOQL pattern, ex: %bacon%. Do not include any quotes.</description>
    <inlineHelpText>See the SOQL Refernce for how to use the LIKE operator</inlineHelpText>
    <label>Test Name Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/UserIds__c.field-meta.xml
<CustomField>
    <fullName>UserIds__c</fullName>
    <description>Users defined here will be emailed the test results. These will be combined with users in any configured profile or permission set.</description>
    <inlineHelpText>Takes a comma-separated list of User IDs</inlineHelpText>
    <label>User Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AutomatedTestRunner.cls
public with sharing class AutomatedTestRunner implements Schedulable {
  static final String THIS_CLASS = 'AutomatedTestRunner';
  static final List<String> STATUSES_TO_SKIP = new List<String>{
    'Holding',
    'Preparing',
    'Processing',
    'Queued'
  };

  @TestVisible
  static List<AutomatedTestSetup__mdt> testSetups;

  @TestVisible
  static List<ApexClass> apexClasses;

  @TestVisible
  final AutomatedTestSetup__mdt testSetup;

  public AutomatedTestRunner(AutomatedTestSetup__mdt testSetup) {
    this.testSetup = testSetup;
  }

  public static void run() {
    reallyRun(null, null);
  }

  public static void run(String testSetupApiName, String cron) {
    if (String.isBlank(testSetupApiName) && String.isBlank(cron)) {
      return;
    }

    reallyRun(testSetupApiName, cron);
  }

  static void reallyRun(String testSetupApiName, String cron) {
    Set<String> alreadyScheduledJobs = new Map<String, SObject>(
        [
          SELECT CronTrigger.CronJobDetail.Name Id
          FROM AsyncApexJob
          WHERE
            ApexClass.Name = :THIS_CLASS
            AND Status IN :STATUSES_TO_SKIP
            AND CronTrigger.CronJobDetail.Name != NULL
          GROUP BY CronTrigger.CronJobDetail.Name
        ]
      ).keySet();

    try {
      for (
        AutomatedTestSetup__mdt testSetup : getAutomatedTestSetups(testSetupApiName)) {
        String cronExp = cron ?? testSetup.Cron__c;
        String jobName = THIS_CLASS + ' ' + testSetup.Label + ' / ' + cronExp;

        if (!alreadyScheduledJobs.contains(jobName)) {
          try {
            System.schedule(jobName, cronExp, new AutomatedTestRunner(testSetup));
          } catch (StringException e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
          }
        }
      }
    } catch (AsyncException e) {
      System.debug(LoggingLevel.ERROR, e.getMessage());
    }
  }

  @TestVisible
  static List<AutomatedTestSetup__mdt> getAutomatedTestSetups(String testSetupApiName) {
    return testSetups ?? Database.query(
        'SELECT ' +
          'Label, ' +
          'Cron__c, ' +
          'ExcludedClasses__c, ' +
          'ExcludedUserIds__c, ' +
          'IncludeNamespacedClasses__c, ' +
          'MinutesToWait__c, ' +
          'PermissionSetToEmail__c, ' +
          'ProfileToEmail__c, ' +
          'ShowStackTrace__c, ' +
          'UserIds__c, ' +
          'TestNamePattern__c ' +
          'FROM AutomatedTestSetup__mdt ' +
          'WHERE ' +
          (testSetupApiName == null
            ? 'IsActive__c = TRUE'
            : 'DeveloperName = \'' + String.escapeSingleQuotes(testSetupApiName) + '\'')
      );
  }

  public void execute(SchedulableContext sc) {
    apexClasses = getApexTestClasses(testSetup);
    if (apexClasses.isEmpty()) {
      return;
    }

    List<ApexTestQueueItem> testQueueItems = createQueueItems(apexClasses);
    Id jobId;

    if (!Test.isRunningTest()) {
      try {
        insert testQueueItems;
      } catch (DmlException e) {
        // womp womp
        System.debug(LoggingLevel.ERROR, e.getMessage());
        return;
      }

      jobId = [
        SELECT ParentJobId
        FROM ApexTestQueueItem
        WHERE Id = :testQueueItems[0].Id
      ].ParentJobId;
    }

    String nextExecutionCron = getNextExecutionCron(testSetup);

    try {
      System.schedule(
        'AutomatedTestReport ' + jobId + ' / ' + nextExecutionCron,
        nextExecutionCron,
        new AutomatedTestReport(testSetup, jobId)
      );
    } catch (AsyncException e) {
      System.debug(LoggingLevel.ERROR, e.getMessage());
    }
  }

  @TestVisible
  static List<ApexClass> getApexTestClasses(AutomatedTestSetup__mdt testSetup) {
    if (apexClasses != null) {
      return apexClasses;
    }

    String queryString = 'FIND \'@istest or testmethod\' IN ALL FIELDS RETURNING ApexClass(Name ';

    Boolean hasWhere = false;
    List<String> excludedClasses;

    if (String.isNotBlank(testSetup.TestNamePattern__c)) {
      queryString +=
        'WHERE Name LIKE \'' +
        String.escapeSingleQuotes(testSetup.TestNamePattern__c) + '\' ';
      hasWhere = true;
    }

    if (!testSetup.IncludeNamespacedClasses__c) {
      queryString += (hasWhere ? 'AND ' : 'WHERE ') + 'NamespacePrefix = NULL ';
      hasWhere = true;
    }

    if (String.isNotBlank(testSetup.ExcludedClasses__c)) {
      excludedClasses = testSetup.ExcludedClasses__c.trim().split('\\s*,\\s*');
      queryString += (hasWhere ? 'AND ' : 'WHERE ') + 'Name NOT IN :excludedClasses ';
    }

    queryString += 'ORDER BY Name)';

    return (List<ApexClass>) Search.query(queryString)[0];
  }

  List<ApexTestQueueItem> createQueueItems(List<ApexClass> apexClasses) {
    List<ApexTestQueueItem> testQueueItems = new List<ApexTestQueueItem>();
    for (ApexClass testClass : apexClasses) {
      testQueueItems.add(new ApexTestQueueItem(ApexClassId = testClass.Id));
    }
    return testQueueItems;
  }

  public static String getNextExecutionCron(AutomatedTestSetup__mdt testSetup) {
    Datetime now = System.now().addMinutes((Integer) testSetup.MinutesToWait__c);

    return '0 ' + // second
      now.format('m') + // minute
      ' ' +
      now.format('H') + // hour
      ' ' +
      now.format('d') + // day
      ' ' +
      now.format('M') + // month
      ' ? ' + // day of week
      now.format('yyyy'); // year
  }
}