force-app/main/default/objects/AutomatedTestSetup__mdt/AutomatedTestSetup__mdt.object-meta.xml
<CustomObject>
    <label>Automated Test Setup</label>
    <pluralLabel>Automated Test Setups</pluralLabel>
</CustomObject>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ExcludedUserIds__c.field-meta.xml
<CustomField>
    <fullName>ExcludedUserIds__c</fullName>
    <description>Users defined here will NOT be emailed, regardless of whether they meet other configured criteria.</description>
    <inlineHelpText>Takes a comma-separated list of User IDs</inlineHelpText>
    <label>Excluded User Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/PermissionSetToEmail__c.field-meta.xml
<CustomField>
    <fullName>PermissionSetToEmail__c</fullName>
    <description>Users of this permission set will be emailed the test results. These will be combined with users in any configured profile or list of user IDs.</description>
    <inlineHelpText>Takes a permission set&apos;s API name</inlineHelpText>
    <label>Permission Set To Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/ProfileToEmail__c.field-meta.xml
<CustomField>
    <fullName>ProfileToEmail__c</fullName>
    <description>Users of this profile will be emailed the test results. These will be combined with users in any configured permission set or list of user IDs.</description>
    <inlineHelpText>Takes a profile name</inlineHelpText>
    <label>Profile To Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomatedTestSetup__mdt/fields/UserIds__c.field-meta.xml
<CustomField>
    <fullName>UserIds__c</fullName>
    <description>Users defined here will be emailed the test results. These will be combined with users in any configured profile or permission set.</description>
    <inlineHelpText>Takes a comma-separated list of User IDs</inlineHelpText>
    <label>User Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AutomatedTestReport_Test.cls
@IsTest
class AutomatedTestReport_Test {
  static final String PROFILE = [SELECT Name FROM Profile LIMIT 1].Name;
  static final String PERMISSION_SET = [SELECT Name FROM PermissionSet LIMIT 1].Name;

  static final String CUSTOM_METADATA_JSON =
    '{"Label": "blah", "ProfileToEmail__c": "' +
    PROFILE +
    '", "PermissionSetToEmail__c": "' +
    PERMISSION_SET +
    '", "UserIds__c": "' +
    UserInfo.getUserId() +
    '", "ExcludedUserIds__c": "005000000000AAA"}';

  static final String TEST_RUN_RESULT_JSON = '{ "Status": "Completed" }';

  static final String TEST_RESULTS_JSON =
    '[ {' +
    '  "MethodName" : "test1",' +
    '  "Outcome" : "Pass",' +
    '  "ApexClass" : {' +
    '    "Name" : "SomeTestClass"' +
    '  }' +
    '}, {' +
    '  "MethodName" : "test2",' +
    '  "Outcome" : "Fail",' +
    '  "ApexClass" : {' +
    '    "Name" : "SomeTestClass"' +
    '  }' +
    '} ]';

  @IsTest
  static void testConstructor() {
    AutomatedTestSetup__mdt testSetup = (AutomatedTestSetup__mdt) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      AutomatedTestSetup__mdt.class
    );

    Test.startTest();
    AutomatedTestReport testReport = new AutomatedTestReport(testSetup, null);
    Test.stopTest();

    Assert.areEqual(testSetup, testReport.testSetup);
  }

  @IsTest
  static void testExecute() {
    AutomatedTestSetup__mdt testSetup = (AutomatedTestSetup__mdt) JSON.deserialize(
      CUSTOM_METADATA_JSON,
      AutomatedTestSetup__mdt.class
    );
    AutomatedTestReport.testRunResult = (ApexTestRunResult) JSON.deserialize(
      TEST_RUN_RESULT_JSON,
      ApexTestRunResult.class
    );
    AutomatedTestReport.testResults = (List<ApexTestResult>) JSON.deserialize(
      TEST_RESULTS_JSON,
      List<ApexTestResult>.class
    );

    Test.startTest();
    System.schedule(
      'AutomatedTestReport',
      '0 0 0 * * ?',
      new AutomatedTestReport(testSetup, null)
    );
    Test.stopTest();

    Integer numberOfScheduledJobs = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status = 'Queued' AND ApexClass.Name = 'AutomatedTestReport'
    ];

    Assert.areEqual(1, numberOfScheduledJobs);
  }
}